/*
OBADA API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
Contact: techops@obada.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/obada-foundation/client-api-library-go

import (
	"encoding/json"
)

// ObitsMeta struct for ObitsMeta
type ObitsMeta struct {
	Total *int32 `json:"total,omitempty"`
	PerPage *int32 `json:"per_page,omitempty"`
	CurrentPage *int32 `json:"current_page,omitempty"`
	LastPage *int32 `json:"last_page,omitempty"`
}

// NewObitsMeta instantiates a new ObitsMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObitsMeta() *ObitsMeta {
	this := ObitsMeta{}
	return &this
}

// NewObitsMetaWithDefaults instantiates a new ObitsMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObitsMetaWithDefaults() *ObitsMeta {
	this := ObitsMeta{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ObitsMeta) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObitsMeta) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ObitsMeta) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ObitsMeta) SetTotal(v int32) {
	o.Total = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *ObitsMeta) GetPerPage() int32 {
	if o == nil || o.PerPage == nil {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObitsMeta) GetPerPageOk() (*int32, bool) {
	if o == nil || o.PerPage == nil {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *ObitsMeta) HasPerPage() bool {
	if o != nil && o.PerPage != nil {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *ObitsMeta) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetCurrentPage returns the CurrentPage field value if set, zero value otherwise.
func (o *ObitsMeta) GetCurrentPage() int32 {
	if o == nil || o.CurrentPage == nil {
		var ret int32
		return ret
	}
	return *o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObitsMeta) GetCurrentPageOk() (*int32, bool) {
	if o == nil || o.CurrentPage == nil {
		return nil, false
	}
	return o.CurrentPage, true
}

// HasCurrentPage returns a boolean if a field has been set.
func (o *ObitsMeta) HasCurrentPage() bool {
	if o != nil && o.CurrentPage != nil {
		return true
	}

	return false
}

// SetCurrentPage gets a reference to the given int32 and assigns it to the CurrentPage field.
func (o *ObitsMeta) SetCurrentPage(v int32) {
	o.CurrentPage = &v
}

// GetLastPage returns the LastPage field value if set, zero value otherwise.
func (o *ObitsMeta) GetLastPage() int32 {
	if o == nil || o.LastPage == nil {
		var ret int32
		return ret
	}
	return *o.LastPage
}

// GetLastPageOk returns a tuple with the LastPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObitsMeta) GetLastPageOk() (*int32, bool) {
	if o == nil || o.LastPage == nil {
		return nil, false
	}
	return o.LastPage, true
}

// HasLastPage returns a boolean if a field has been set.
func (o *ObitsMeta) HasLastPage() bool {
	if o != nil && o.LastPage != nil {
		return true
	}

	return false
}

// SetLastPage gets a reference to the given int32 and assigns it to the LastPage field.
func (o *ObitsMeta) SetLastPage(v int32) {
	o.LastPage = &v
}

func (o ObitsMeta) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	if o.PerPage != nil {
		toSerialize["per_page"] = o.PerPage
	}
	if o.CurrentPage != nil {
		toSerialize["current_page"] = o.CurrentPage
	}
	if o.LastPage != nil {
		toSerialize["last_page"] = o.LastPage
	}
	return json.Marshal(toSerialize)
}

type NullableObitsMeta struct {
	value *ObitsMeta
	isSet bool
}

func (v NullableObitsMeta) Get() *ObitsMeta {
	return v.value
}

func (v *NullableObitsMeta) Set(val *ObitsMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableObitsMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableObitsMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObitsMeta(val *ObitsMeta) *NullableObitsMeta {
	return &NullableObitsMeta{value: val, isSet: true}
}

func (v NullableObitsMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObitsMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


