/*
OBADA API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
Contact: techops@obada.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/obada-foundation/client-api-library-go

import (
	"encoding/json"
)

// GenerateObitDIDRequest Generate Obit DID payload
type GenerateObitDIDRequest struct {
	// Manufacturer (Required)
	Manufacturer string `json:"manufacturer"`
	// Part Number (Required)
	PartNumber string `json:"part_number"`
	// Serial Number (Required)
	SerialNumber string `json:"serial_number"`
}

// NewGenerateObitDIDRequest instantiates a new GenerateObitDIDRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateObitDIDRequest(manufacturer string, partNumber string, serialNumber string) *GenerateObitDIDRequest {
	this := GenerateObitDIDRequest{}
	this.Manufacturer = manufacturer
	this.PartNumber = partNumber
	this.SerialNumber = serialNumber
	return &this
}

// NewGenerateObitDIDRequestWithDefaults instantiates a new GenerateObitDIDRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateObitDIDRequestWithDefaults() *GenerateObitDIDRequest {
	this := GenerateObitDIDRequest{}
	return &this
}

// GetManufacturer returns the Manufacturer field value
func (o *GenerateObitDIDRequest) GetManufacturer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value
// and a boolean to check if the value has been set.
func (o *GenerateObitDIDRequest) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Manufacturer, true
}

// SetManufacturer sets field value
func (o *GenerateObitDIDRequest) SetManufacturer(v string) {
	o.Manufacturer = v
}

// GetPartNumber returns the PartNumber field value
func (o *GenerateObitDIDRequest) GetPartNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartNumber
}

// GetPartNumberOk returns a tuple with the PartNumber field value
// and a boolean to check if the value has been set.
func (o *GenerateObitDIDRequest) GetPartNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartNumber, true
}

// SetPartNumber sets field value
func (o *GenerateObitDIDRequest) SetPartNumber(v string) {
	o.PartNumber = v
}

// GetSerialNumber returns the SerialNumber field value
func (o *GenerateObitDIDRequest) GetSerialNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value
// and a boolean to check if the value has been set.
func (o *GenerateObitDIDRequest) GetSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SerialNumber, true
}

// SetSerialNumber sets field value
func (o *GenerateObitDIDRequest) SetSerialNumber(v string) {
	o.SerialNumber = v
}

func (o GenerateObitDIDRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["manufacturer"] = o.Manufacturer
	}
	if true {
		toSerialize["part_number"] = o.PartNumber
	}
	if true {
		toSerialize["serial_number"] = o.SerialNumber
	}
	return json.Marshal(toSerialize)
}

type NullableGenerateObitDIDRequest struct {
	value *GenerateObitDIDRequest
	isSet bool
}

func (v NullableGenerateObitDIDRequest) Get() *GenerateObitDIDRequest {
	return v.value
}

func (v *NullableGenerateObitDIDRequest) Set(val *GenerateObitDIDRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateObitDIDRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateObitDIDRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateObitDIDRequest(val *GenerateObitDIDRequest) *NullableGenerateObitDIDRequest {
	return &NullableGenerateObitDIDRequest{value: val, isSet: true}
}

func (v NullableGenerateObitDIDRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateObitDIDRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


