/*
OBADA API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
Contact: techops@obada.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/obada-foundation/client-api-library-go

import (
	"encoding/json"
)

// NewAccountRequest New account create payload
type NewAccountRequest struct {
	// Account owner email, will be used for verification purpose
	Email string `json:"email"`
}

// NewNewAccountRequest instantiates a new NewAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewAccountRequest(email string) *NewAccountRequest {
	this := NewAccountRequest{}
	this.Email = email
	return &this
}

// NewNewAccountRequestWithDefaults instantiates a new NewAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewAccountRequestWithDefaults() *NewAccountRequest {
	this := NewAccountRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *NewAccountRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *NewAccountRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *NewAccountRequest) SetEmail(v string) {
	o.Email = v
}

func (o NewAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["email"] = o.Email
	}
	return json.Marshal(toSerialize)
}

type NullableNewAccountRequest struct {
	value *NewAccountRequest
	isSet bool
}

func (v NullableNewAccountRequest) Get() *NewAccountRequest {
	return v.value
}

func (v *NullableNewAccountRequest) Set(val *NewAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNewAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNewAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewAccountRequest(val *NewAccountRequest) *NullableNewAccountRequest {
	return &NullableNewAccountRequest{value: val, isSet: true}
}

func (v NullableNewAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


