/*
OBADA API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
Contact: techops@obada.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/obada-foundation/client-api-library-go

import (
	"encoding/json"
)

// GenerateObitChecksumRequest Generate Obit checksum payload
type GenerateObitChecksumRequest struct {
	// Manufacturer (Required)
	Manufacturer string `json:"manufacturer"`
	// Part Number (Required)
	PartNumber string `json:"part_number"`
	// Serial Number (Required)
	SerialNumber string `json:"serial_number"`
	// Metadata URI
	MetadataUri *string `json:"metadata_uri,omitempty"`
	// Metadata URI Hash
	MetadataUriHash *string `json:"metadata_uri_hash,omitempty"`
	// Trust Token
	TrustAnchorToken *string `json:"trust_anchor_token,omitempty"`
}

// NewGenerateObitChecksumRequest instantiates a new GenerateObitChecksumRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateObitChecksumRequest(manufacturer string, partNumber string, serialNumber string) *GenerateObitChecksumRequest {
	this := GenerateObitChecksumRequest{}
	this.Manufacturer = manufacturer
	this.PartNumber = partNumber
	this.SerialNumber = serialNumber
	return &this
}

// NewGenerateObitChecksumRequestWithDefaults instantiates a new GenerateObitChecksumRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateObitChecksumRequestWithDefaults() *GenerateObitChecksumRequest {
	this := GenerateObitChecksumRequest{}
	return &this
}

// GetManufacturer returns the Manufacturer field value
func (o *GenerateObitChecksumRequest) GetManufacturer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value
// and a boolean to check if the value has been set.
func (o *GenerateObitChecksumRequest) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Manufacturer, true
}

// SetManufacturer sets field value
func (o *GenerateObitChecksumRequest) SetManufacturer(v string) {
	o.Manufacturer = v
}

// GetPartNumber returns the PartNumber field value
func (o *GenerateObitChecksumRequest) GetPartNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartNumber
}

// GetPartNumberOk returns a tuple with the PartNumber field value
// and a boolean to check if the value has been set.
func (o *GenerateObitChecksumRequest) GetPartNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartNumber, true
}

// SetPartNumber sets field value
func (o *GenerateObitChecksumRequest) SetPartNumber(v string) {
	o.PartNumber = v
}

// GetSerialNumber returns the SerialNumber field value
func (o *GenerateObitChecksumRequest) GetSerialNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value
// and a boolean to check if the value has been set.
func (o *GenerateObitChecksumRequest) GetSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SerialNumber, true
}

// SetSerialNumber sets field value
func (o *GenerateObitChecksumRequest) SetSerialNumber(v string) {
	o.SerialNumber = v
}

// GetMetadataUri returns the MetadataUri field value if set, zero value otherwise.
func (o *GenerateObitChecksumRequest) GetMetadataUri() string {
	if o == nil || o.MetadataUri == nil {
		var ret string
		return ret
	}
	return *o.MetadataUri
}

// GetMetadataUriOk returns a tuple with the MetadataUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateObitChecksumRequest) GetMetadataUriOk() (*string, bool) {
	if o == nil || o.MetadataUri == nil {
		return nil, false
	}
	return o.MetadataUri, true
}

// HasMetadataUri returns a boolean if a field has been set.
func (o *GenerateObitChecksumRequest) HasMetadataUri() bool {
	if o != nil && o.MetadataUri != nil {
		return true
	}

	return false
}

// SetMetadataUri gets a reference to the given string and assigns it to the MetadataUri field.
func (o *GenerateObitChecksumRequest) SetMetadataUri(v string) {
	o.MetadataUri = &v
}

// GetMetadataUriHash returns the MetadataUriHash field value if set, zero value otherwise.
func (o *GenerateObitChecksumRequest) GetMetadataUriHash() string {
	if o == nil || o.MetadataUriHash == nil {
		var ret string
		return ret
	}
	return *o.MetadataUriHash
}

// GetMetadataUriHashOk returns a tuple with the MetadataUriHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateObitChecksumRequest) GetMetadataUriHashOk() (*string, bool) {
	if o == nil || o.MetadataUriHash == nil {
		return nil, false
	}
	return o.MetadataUriHash, true
}

// HasMetadataUriHash returns a boolean if a field has been set.
func (o *GenerateObitChecksumRequest) HasMetadataUriHash() bool {
	if o != nil && o.MetadataUriHash != nil {
		return true
	}

	return false
}

// SetMetadataUriHash gets a reference to the given string and assigns it to the MetadataUriHash field.
func (o *GenerateObitChecksumRequest) SetMetadataUriHash(v string) {
	o.MetadataUriHash = &v
}

// GetTrustAnchorToken returns the TrustAnchorToken field value if set, zero value otherwise.
func (o *GenerateObitChecksumRequest) GetTrustAnchorToken() string {
	if o == nil || o.TrustAnchorToken == nil {
		var ret string
		return ret
	}
	return *o.TrustAnchorToken
}

// GetTrustAnchorTokenOk returns a tuple with the TrustAnchorToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateObitChecksumRequest) GetTrustAnchorTokenOk() (*string, bool) {
	if o == nil || o.TrustAnchorToken == nil {
		return nil, false
	}
	return o.TrustAnchorToken, true
}

// HasTrustAnchorToken returns a boolean if a field has been set.
func (o *GenerateObitChecksumRequest) HasTrustAnchorToken() bool {
	if o != nil && o.TrustAnchorToken != nil {
		return true
	}

	return false
}

// SetTrustAnchorToken gets a reference to the given string and assigns it to the TrustAnchorToken field.
func (o *GenerateObitChecksumRequest) SetTrustAnchorToken(v string) {
	o.TrustAnchorToken = &v
}

func (o GenerateObitChecksumRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["manufacturer"] = o.Manufacturer
	}
	if true {
		toSerialize["part_number"] = o.PartNumber
	}
	if true {
		toSerialize["serial_number"] = o.SerialNumber
	}
	if o.MetadataUri != nil {
		toSerialize["metadata_uri"] = o.MetadataUri
	}
	if o.MetadataUriHash != nil {
		toSerialize["metadata_uri_hash"] = o.MetadataUriHash
	}
	if o.TrustAnchorToken != nil {
		toSerialize["trust_anchor_token"] = o.TrustAnchorToken
	}
	return json.Marshal(toSerialize)
}

type NullableGenerateObitChecksumRequest struct {
	value *GenerateObitChecksumRequest
	isSet bool
}

func (v NullableGenerateObitChecksumRequest) Get() *GenerateObitChecksumRequest {
	return v.value
}

func (v *NullableGenerateObitChecksumRequest) Set(val *GenerateObitChecksumRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateObitChecksumRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateObitChecksumRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateObitChecksumRequest(val *GenerateObitChecksumRequest) *NullableGenerateObitChecksumRequest {
	return &NullableGenerateObitChecksumRequest{value: val, isSet: true}
}

func (v NullableGenerateObitChecksumRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateObitChecksumRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


