/*
OBADA API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
Contact: techops@obada.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/obada-foundation/client-api-library-go

import (
	"encoding/json"
)

// WalletExistsError Returns when trying to create or import HD wallet into setteld user profile.
type WalletExistsError struct {
	Error *string `json:"error,omitempty"`
}

// NewWalletExistsError instantiates a new WalletExistsError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletExistsError() *WalletExistsError {
	this := WalletExistsError{}
	var error_ string = "profile wallet already exist"
	this.Error = &error_
	return &this
}

// NewWalletExistsErrorWithDefaults instantiates a new WalletExistsError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletExistsErrorWithDefaults() *WalletExistsError {
	this := WalletExistsError{}
	var error_ string = "profile wallet already exist"
	this.Error = &error_
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *WalletExistsError) GetError() string {
	if o == nil || o.Error == nil {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletExistsError) GetErrorOk() (*string, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *WalletExistsError) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *WalletExistsError) SetError(v string) {
	o.Error = &v
}

func (o WalletExistsError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableWalletExistsError struct {
	value *WalletExistsError
	isSet bool
}

func (v NullableWalletExistsError) Get() *WalletExistsError {
	return v.value
}

func (v *NullableWalletExistsError) Set(val *WalletExistsError) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletExistsError) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletExistsError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletExistsError(val *WalletExistsError) *NullableWalletExistsError {
	return &NullableWalletExistsError{value: val, isSet: true}
}

func (v NullableWalletExistsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletExistsError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


