/*
OBADA API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
Contact: techops@obada.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/obada-foundation/client-api-library-go

import (
	"encoding/json"
)

// SendCoinsRequest Sending tokens payload
type SendCoinsRequest struct {
	RecepientAddress string `json:"recepient_address"`
	Amount string `json:"amount"`
	Denom string `json:"denom"`
}

// NewSendCoinsRequest instantiates a new SendCoinsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendCoinsRequest(recepientAddress string, amount string, denom string) *SendCoinsRequest {
	this := SendCoinsRequest{}
	this.RecepientAddress = recepientAddress
	this.Amount = amount
	this.Denom = denom
	return &this
}

// NewSendCoinsRequestWithDefaults instantiates a new SendCoinsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendCoinsRequestWithDefaults() *SendCoinsRequest {
	this := SendCoinsRequest{}
	return &this
}

// GetRecepientAddress returns the RecepientAddress field value
func (o *SendCoinsRequest) GetRecepientAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecepientAddress
}

// GetRecepientAddressOk returns a tuple with the RecepientAddress field value
// and a boolean to check if the value has been set.
func (o *SendCoinsRequest) GetRecepientAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecepientAddress, true
}

// SetRecepientAddress sets field value
func (o *SendCoinsRequest) SetRecepientAddress(v string) {
	o.RecepientAddress = v
}

// GetAmount returns the Amount field value
func (o *SendCoinsRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *SendCoinsRequest) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *SendCoinsRequest) SetAmount(v string) {
	o.Amount = v
}

// GetDenom returns the Denom field value
func (o *SendCoinsRequest) GetDenom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Denom
}

// GetDenomOk returns a tuple with the Denom field value
// and a boolean to check if the value has been set.
func (o *SendCoinsRequest) GetDenomOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Denom, true
}

// SetDenom sets field value
func (o *SendCoinsRequest) SetDenom(v string) {
	o.Denom = v
}

func (o SendCoinsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["recepient_address"] = o.RecepientAddress
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["denom"] = o.Denom
	}
	return json.Marshal(toSerialize)
}

type NullableSendCoinsRequest struct {
	value *SendCoinsRequest
	isSet bool
}

func (v NullableSendCoinsRequest) Get() *SendCoinsRequest {
	return v.value
}

func (v *NullableSendCoinsRequest) Set(val *SendCoinsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendCoinsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendCoinsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendCoinsRequest(val *SendCoinsRequest) *NullableSendCoinsRequest {
	return &NullableSendCoinsRequest{value: val, isSet: true}
}

func (v NullableSendCoinsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendCoinsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


