/*
OBADA Client Helper API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
Contact: techops@obada.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/obada-foundation/client-api-library-go

import (
	"encoding/json"
)

// LocalObitDocumentsInner Document hashlink
type LocalObitDocumentsInner struct {
	// Associative name of hashlink
	Name string `json:"name"`
	// Hashlink
	Hashlink string `json:"hashlink"`
}

// NewLocalObitDocumentsInner instantiates a new LocalObitDocumentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocalObitDocumentsInner(name string, hashlink string) *LocalObitDocumentsInner {
	this := LocalObitDocumentsInner{}
	this.Name = name
	this.Hashlink = hashlink
	return &this
}

// NewLocalObitDocumentsInnerWithDefaults instantiates a new LocalObitDocumentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocalObitDocumentsInnerWithDefaults() *LocalObitDocumentsInner {
	this := LocalObitDocumentsInner{}
	return &this
}

// GetName returns the Name field value
func (o *LocalObitDocumentsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LocalObitDocumentsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LocalObitDocumentsInner) SetName(v string) {
	o.Name = v
}

// GetHashlink returns the Hashlink field value
func (o *LocalObitDocumentsInner) GetHashlink() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hashlink
}

// GetHashlinkOk returns a tuple with the Hashlink field value
// and a boolean to check if the value has been set.
func (o *LocalObitDocumentsInner) GetHashlinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hashlink, true
}

// SetHashlink sets field value
func (o *LocalObitDocumentsInner) SetHashlink(v string) {
	o.Hashlink = v
}

func (o LocalObitDocumentsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["hashlink"] = o.Hashlink
	}
	return json.Marshal(toSerialize)
}

type NullableLocalObitDocumentsInner struct {
	value *LocalObitDocumentsInner
	isSet bool
}

func (v NullableLocalObitDocumentsInner) Get() *LocalObitDocumentsInner {
	return v.value
}

func (v *NullableLocalObitDocumentsInner) Set(val *LocalObitDocumentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableLocalObitDocumentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableLocalObitDocumentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocalObitDocumentsInner(val *LocalObitDocumentsInner) *NullableLocalObitDocumentsInner {
	return &NullableLocalObitDocumentsInner{value: val, isSet: true}
}

func (v NullableLocalObitDocumentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocalObitDocumentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


