/*
 * OBADA Client Helper API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Contact: techops@obada.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/obada-foundation/client-api-library-go

import (
	"encoding/json"
)

// BlockChainObitResponse struct for BlockChainObitResponse
type BlockChainObitResponse struct {
	Status *int32 `json:"status,omitempty"`
	BlockchainObit *BlockChainObit `json:"blockchain_obit,omitempty"`
}

// NewBlockChainObitResponse instantiates a new BlockChainObitResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockChainObitResponse() *BlockChainObitResponse {
	this := BlockChainObitResponse{}
	return &this
}

// NewBlockChainObitResponseWithDefaults instantiates a new BlockChainObitResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockChainObitResponseWithDefaults() *BlockChainObitResponse {
	this := BlockChainObitResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BlockChainObitResponse) GetStatus() int32 {
	if o == nil || o.Status == nil {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockChainObitResponse) GetStatusOk() (*int32, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BlockChainObitResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *BlockChainObitResponse) SetStatus(v int32) {
	o.Status = &v
}

// GetBlockchainObit returns the BlockchainObit field value if set, zero value otherwise.
func (o *BlockChainObitResponse) GetBlockchainObit() BlockChainObit {
	if o == nil || o.BlockchainObit == nil {
		var ret BlockChainObit
		return ret
	}
	return *o.BlockchainObit
}

// GetBlockchainObitOk returns a tuple with the BlockchainObit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockChainObitResponse) GetBlockchainObitOk() (*BlockChainObit, bool) {
	if o == nil || o.BlockchainObit == nil {
		return nil, false
	}
	return o.BlockchainObit, true
}

// HasBlockchainObit returns a boolean if a field has been set.
func (o *BlockChainObitResponse) HasBlockchainObit() bool {
	if o != nil && o.BlockchainObit != nil {
		return true
	}

	return false
}

// SetBlockchainObit gets a reference to the given BlockChainObit and assigns it to the BlockchainObit field.
func (o *BlockChainObitResponse) SetBlockchainObit(v BlockChainObit) {
	o.BlockchainObit = &v
}

func (o BlockChainObitResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.BlockchainObit != nil {
		toSerialize["blockchain_obit"] = o.BlockchainObit
	}
	return json.Marshal(toSerialize)
}

type NullableBlockChainObitResponse struct {
	value *BlockChainObitResponse
	isSet bool
}

func (v NullableBlockChainObitResponse) Get() *BlockChainObitResponse {
	return v.value
}

func (v *NullableBlockChainObitResponse) Set(val *BlockChainObitResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockChainObitResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockChainObitResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockChainObitResponse(val *BlockChainObitResponse) *NullableBlockChainObitResponse {
	return &NullableBlockChainObitResponse{value: val, isSet: true}
}

func (v NullableBlockChainObitResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockChainObitResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


