/*
OBADA API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
Contact: techops@obada.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/obada-foundation/client-api-library-go

import (
	"encoding/json"
)

// UnprocessableEntityFieldsInner struct for UnprocessableEntityFieldsInner
type UnprocessableEntityFieldsInner struct {
	Field *string `json:"field,omitempty"`
	Error *string `json:"error,omitempty"`
}

// NewUnprocessableEntityFieldsInner instantiates a new UnprocessableEntityFieldsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnprocessableEntityFieldsInner() *UnprocessableEntityFieldsInner {
	this := UnprocessableEntityFieldsInner{}
	var field string = "serial_number"
	this.Field = &field
	var error_ string = "serial_number is required field"
	this.Error = &error_
	return &this
}

// NewUnprocessableEntityFieldsInnerWithDefaults instantiates a new UnprocessableEntityFieldsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnprocessableEntityFieldsInnerWithDefaults() *UnprocessableEntityFieldsInner {
	this := UnprocessableEntityFieldsInner{}
	var field string = "serial_number"
	this.Field = &field
	var error_ string = "serial_number is required field"
	this.Error = &error_
	return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *UnprocessableEntityFieldsInner) GetField() string {
	if o == nil || o.Field == nil {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnprocessableEntityFieldsInner) GetFieldOk() (*string, bool) {
	if o == nil || o.Field == nil {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *UnprocessableEntityFieldsInner) HasField() bool {
	if o != nil && o.Field != nil {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *UnprocessableEntityFieldsInner) SetField(v string) {
	o.Field = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *UnprocessableEntityFieldsInner) GetError() string {
	if o == nil || o.Error == nil {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnprocessableEntityFieldsInner) GetErrorOk() (*string, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *UnprocessableEntityFieldsInner) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *UnprocessableEntityFieldsInner) SetError(v string) {
	o.Error = &v
}

func (o UnprocessableEntityFieldsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Field != nil {
		toSerialize["field"] = o.Field
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableUnprocessableEntityFieldsInner struct {
	value *UnprocessableEntityFieldsInner
	isSet bool
}

func (v NullableUnprocessableEntityFieldsInner) Get() *UnprocessableEntityFieldsInner {
	return v.value
}

func (v *NullableUnprocessableEntityFieldsInner) Set(val *UnprocessableEntityFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUnprocessableEntityFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUnprocessableEntityFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnprocessableEntityFieldsInner(val *UnprocessableEntityFieldsInner) *NullableUnprocessableEntityFieldsInner {
	return &NullableUnprocessableEntityFieldsInner{value: val, isSet: true}
}

func (v NullableUnprocessableEntityFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnprocessableEntityFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


