/*
OBADA API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
Contact: techops@obada.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github.com/obada-foundation/client-api-library-go

import (
	"encoding/json"
)

// SaveObitRequest Request to save Obit
type SaveObitRequest struct {
	// Waiting more specific details from Rohi
	Manufacturer string `json:"manufacturer"`
	// Manufacturer provided. In cases where no part number is provided for the product, use model, or the most specific ID available from the manufacturer. MWCN2LL/A (an iPhone 11 Pro, Silver, 256GB, model A2160)
	PartNumber string `json:"part_number"`
	// Serial number hashed with sha256 hash function
	SerialNumber string `json:"serial_number"`
	Documents []DeviceDocument `json:"documents,omitempty"`
	Address *string `json:"address,omitempty"`
}

// NewSaveObitRequest instantiates a new SaveObitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSaveObitRequest(manufacturer string, partNumber string, serialNumber string) *SaveObitRequest {
	this := SaveObitRequest{}
	this.Manufacturer = manufacturer
	this.PartNumber = partNumber
	this.SerialNumber = serialNumber
	return &this
}

// NewSaveObitRequestWithDefaults instantiates a new SaveObitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSaveObitRequestWithDefaults() *SaveObitRequest {
	this := SaveObitRequest{}
	return &this
}

// GetManufacturer returns the Manufacturer field value
func (o *SaveObitRequest) GetManufacturer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value
// and a boolean to check if the value has been set.
func (o *SaveObitRequest) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Manufacturer, true
}

// SetManufacturer sets field value
func (o *SaveObitRequest) SetManufacturer(v string) {
	o.Manufacturer = v
}

// GetPartNumber returns the PartNumber field value
func (o *SaveObitRequest) GetPartNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartNumber
}

// GetPartNumberOk returns a tuple with the PartNumber field value
// and a boolean to check if the value has been set.
func (o *SaveObitRequest) GetPartNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartNumber, true
}

// SetPartNumber sets field value
func (o *SaveObitRequest) SetPartNumber(v string) {
	o.PartNumber = v
}

// GetSerialNumber returns the SerialNumber field value
func (o *SaveObitRequest) GetSerialNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value
// and a boolean to check if the value has been set.
func (o *SaveObitRequest) GetSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SerialNumber, true
}

// SetSerialNumber sets field value
func (o *SaveObitRequest) SetSerialNumber(v string) {
	o.SerialNumber = v
}

// GetDocuments returns the Documents field value if set, zero value otherwise.
func (o *SaveObitRequest) GetDocuments() []DeviceDocument {
	if o == nil || o.Documents == nil {
		var ret []DeviceDocument
		return ret
	}
	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SaveObitRequest) GetDocumentsOk() ([]DeviceDocument, bool) {
	if o == nil || o.Documents == nil {
		return nil, false
	}
	return o.Documents, true
}

// HasDocuments returns a boolean if a field has been set.
func (o *SaveObitRequest) HasDocuments() bool {
	if o != nil && o.Documents != nil {
		return true
	}

	return false
}

// SetDocuments gets a reference to the given []DeviceDocument and assigns it to the Documents field.
func (o *SaveObitRequest) SetDocuments(v []DeviceDocument) {
	o.Documents = v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *SaveObitRequest) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SaveObitRequest) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *SaveObitRequest) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *SaveObitRequest) SetAddress(v string) {
	o.Address = &v
}

func (o SaveObitRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["manufacturer"] = o.Manufacturer
	}
	if true {
		toSerialize["part_number"] = o.PartNumber
	}
	if true {
		toSerialize["serial_number"] = o.SerialNumber
	}
	if o.Documents != nil {
		toSerialize["documents"] = o.Documents
	}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	return json.Marshal(toSerialize)
}

type NullableSaveObitRequest struct {
	value *SaveObitRequest
	isSet bool
}

func (v NullableSaveObitRequest) Get() *SaveObitRequest {
	return v.value
}

func (v *NullableSaveObitRequest) Set(val *SaveObitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSaveObitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSaveObitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSaveObitRequest(val *SaveObitRequest) *NullableSaveObitRequest {
	return &NullableSaveObitRequest{value: val, isSet: true}
}

func (v NullableSaveObitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSaveObitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


